parameters:
    tjtDigi    : '%kernel.project_dir%/public_html/data/'
    empTkWorker: '%kernel.project_dir%/public_html/tks/'
    repoImg    : '%kernel.project_dir%/public_html/repo_img/'
    invImg     : '%kernel.project_dir%/public_html/images/inv/'

    avatarTipos: '%kernel.project_dir%/public_html/images/avatar_tipos/'
    pubImg     : '%kernel.project_dir%/public_html/empresas/pubs/'
    empLogo    : '%kernel.project_dir%/public_html/empresas/logos/'
    empFacha   : '%kernel.project_dir%/public_html/empresas/fachadas/'
    toCotizar  : '%kernel.project_dir%/public_html/taller/web/pictures/to_cotizar/_repomain_/'
    
    roles: [
        'Asesores de Ventas->ADMIN_AVO',
        'Ejecutvos de Ventas->ADMIN_EVO',
    ]

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']