parameters:
    phtml      : '%kernel.project_dir%/public_html'
    tjtDigi    : '%phtml%/data/'
    empTkWorker: '%phtml%/tks/'
    eyesPro    : '%phtml%/eyes_pro/'
    whoTestPush: '%phtml%/test_push/'
    repoImg    : '%phtml%/repo_img/'
    invImg     : '%phtml%/images/inv/'

    avatarTipos: '%phtml%/images/avatar_tipos/'
    pubImg     : '%phtml%/empresas/pubs/'
    empLogo    : '%phtml%/empresas/logos/'
    empFacha   : '%phtml%/empresas/fachadas/'
    toCotizar  : '%phtml%/cotiza/pictures/to_cotizar/_repomain_/'
    toCotizarSh: '%phtml%/cotiza/pictures/to_cotizar/_repomain_/shared/'
    cotizadas  : '%phtml%/cotiza/pictures/cotizadas/_repomain_/_idinfo_/'
    sharedCtz  : '%phtml%/cotiza/pictures/cotizadas/shared/_idPza_/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']